=== BackupTheBerlios/quiztestxml/quiz/xml/quiztext-0.1.dtd
<!-- ============================================================== -->
<!-- Quiz Text DTD ================================================ -->
<!-- file: quiztech.DTD

  This is quiztext 0.1

		Copyright: 2003 by Andre Krause, Stephan Bischoff und 
				   Sebastian Knapp

		Author: Sebstian Knapp     
        Revision:   2003/06/20/ Sebastian Knapp  

     This DTD module is identified by the PUBLIC and SYSTEM identifiers:

     PUBLIC "-//SRGL//ELEMENTS QUIZ-TEXT 0.1 APPLICATION//EN"
     SYSTEM "http://www.ccls-online.de/2003/quiztext-0.1.dtd"

     ============================================================== -->

<!-- ==============================================================

	 Hier werden sämtliche Tags aufgelistet, die ein gültiges quiztext
      Dokument enthalten darf. Aussedem wird definiert welche Kindelemente
     das jeweilige Element enthalten darf.
     
     	 keine Anzahl spezifiziert - muss einmal vorkommen
     	 ? - kann ein oder keinmal vorkommen
     	 + - muss ein oder mehrfach vorkommen
     	 * - kann nullmal, einmal oder mehrfach vorkommen
     	 
     	 #PCDATA - Element enthält Daten
     	 
     	 , - liest sich wie UND 
     	 | -   "     "    " ODER
     	 
     =============================================================== -->     	 

<!ELEMENT quiz (questionset+)>
	<!ELEMENT questionset (creation_date?,
						   editor*,
						   title,
						   abstract?,
						   quizentry+,
						   resultset? ) >
		<!ELEMENT creation_date (#PCDATA)>
		<!ELEMENT editor (name,email?)>
			<!ELEMENT name (#PCDATA)>
			<!ELEMENT email (#PCDATA)>
		<!ELEMENT title (#PCDATA)>
		<!ELEMENT abstract (#PCDATA)>
		<!ELEMENT quizentry ( question,hint*,image*,
								( (answer,fullanswer?) |
								 test+				|
								 choice+			|
								 sortitem+ ) )>
			<!ELEMENT question (#PCDATA)>
			<!ELEMENT hint (#PCDATA)>
			<!ELEMENT image (#PCDATA)>
			<!ELEMENT answer  (#PCDATA)>
			<!ELEMENT fullanswer  (#PCDATA)>
			<!ELEMENT test (#PCDATA)>
			<!ELEMENT choice (#PCDATA)>
			<!ELEMENT sortitem (#PCDATA)>
		<!ELEMENT resultset (result+)>
			<!ELEMENT result (#PCDATA)>
			 

<!-- ===============================================================

	  Hier wird definiert welche Attribute ein Element enthält.
	  
	  		CDATA - alle Zeichen ausser '<', '>', '"' und '&' sind
	  		         erlaubt.
	  		         
	  		         
	  		#IMPLIED - Attribut ist optional.
	  		#REQUIRED - Attribut ist nicht optional.
	  		
     =============================================================== -->

<!-- source - eine Quellenangabe für das Element                    -->
<!ATTLIST questionset
	SID		ID		#REQUIRED
	source   CDATA #IMPLIED
	language CDATA #IMPLIED>

<!ATTLIST quizentry
	source CDATA #IMPLIED>
			
<!ATTLIST question 
	source CDATA #IMPLIED>
	
<!ATTLIST answer
	source CDATA #IMPLIED>
	
<!ATTLIST fullanswer
	source CDATA #IMPLIED>
	
<!ATTLIST hint
	source CDATA #IMPLIED>

<!-- ref - Adresse der Bilddatei, enweder als absolute URL oder 
			relativ zu einem Wurzelverzeichnis                      -->	
<!ATTLIST image
	source CDATA #IMPLIED
	ref	 CDATA #REQUIRED>

<!-- Werte sind vordefiniert. "false" wird als Standardwert gesetzt. -->
<!ATTLIST choice
	correct (true|false) "false">
	
<!ATTLIST sortitem
	position CDATA #REQUIRED>
	
<!ATTLIST test
	value CDATA #REQUIRED>
	
<!ATTLIST result
	minimum CDATA #REQUIRED
	maximum CDATA #REQUIRED>

=== BackupTheBerlios/quiztestxml/quiz/xml/fahrschule.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quiztext SYSTEM "quiztext-0.1.dtd"><quiz>
	<questionset SID="fahr0">
		<creation_date>
		2003-06-20
		</creation_date>
		<editor>
			<name>
			Stefan Bischoff
			</name>
			<email>
			giftnudel185@web.de
			</email>
		</editor>
		<title>
		 Fahrschulquiz
		</title>
		<abstract>
		</abstract>
		<quizentry>
			<question>
			 Welche Besonderheiten ergeben sich beim Befahren von Alleen ?
			</question>
			<choice correct="false">
			 Die Bäume verschaffen seitlichen Schutz.
			</choice>
			<choice correct="true">
			 Kurven sind oft besonders eng und unübersichtlich.
			</choice>
			<choice correct="true">
			 Geringe Breite der Fahrbahn und ihre gewölbte Form zwingen bei Gegenverkehr zubesonderer Vorsicht.
			</choice>
		</quizentry>
		<quizentry>
			<question>
			 Bei stockenden Verkehr müssen bestimmte Bereiche freigehalten werden.
         Welche sind das ?
			</question>
			<choice correct="true">
			 Kreuzungen
			</choice>
			<choice correct="false">
			 Grundstückseinfahrten
			</choice>
                        <choice correct="true">
			 Bahnübergänge
			</choice>
		</quizentry>
		<quizentry>
			<question>
			 Wann dürfen Sie auch am Tage Nebelscheinwerfer einschalten ?
         Bei erheblicher Sichtbehinderung durch
			</question>
			<choice correct="true">
			 Nebel oder Schneefall
			</choice>
                        <choice correct="true">
			Regen
			</choice>
			<choice correct="false">
			 Eis auf der Windschutzscheibe
			</choice>
		</quizentry>
		<quizentry>
			<question>
			 Was zeigt die sechseckige Plakette auf dem vorderen Nummernschild an ?
     Den Termin für
			</question>
			<choice correct="false">
			 die nächste Hauptuntersuchung
			</choice>
			<choice correct="false">
			 die Fälligkeit der Kraftfahrzeugsteuer
			</choice>
                        <choice correct="true">
                        die nächste Abgasuntersuchung
                        </choice>
		</quizentry>
		<quizentry>
			<question>
			 Was bedeutet dieser Warnhinweis ?
     Auf einem so gekennzeichneten Beifahrerplatz mit betriebsbereitem Airbag
			</question>
            <image ref="airbag.jpg"></image>
			<choice correct="false">
			 darf ein Kindersitz entgegen der Fahrtrichtung angebracht werden
			</choice>
			<choice correct="false">
			 muss der Kindersitz in der dargestellten Weise angebracht werden
			</choice>
                        <choice correct="true">
                        darf ein Kindersitz nur in Fahrtrichtung angebracht werden  
                        </choice>  
		</quizentry>
		<quizentry>
			<question>
			 Wie Verhalten Sie sich bei diesem Verkehrszeichen ?
			</question>
			<image ref="rechtsvorlinks.jpg"></image>
			<choice correct="false">
			 Nur den von rechts kommenden Verkehr beobachten
			</choice>
			<choice correct="true">
			 Bremsbereit sein
			</choice>
			<choice correct="true">
			 Geschwindigkeit vermindern
			</choice>
		</quizentry>
		<quizentry>
			<question>
			 Worauf weist dieses Verkehrszeichen hin ?
			</question>
			<image ref="Spielstrasse.JPG"></image>
			<choice correct="true">
			 Auf das Ende eines verkehrsberuhigten Bereichs
			</choice>
			<choice correct="false">
			 Auf ein Verbot für Fußgänger und Krafwagen
			</choice>
		</quizentry>
		<quizentry>
			<question>
			 Um welche Zeit endet das Fahrverbot an Sonn- und Feiertagen für LKW's ?
			 </question>
			 <answer>22 Uhr </answer>  
			 <answer> 22 </answer>
    		</quizentry>
		<quizentry>
			<question>
			 Wie schnell darf ein Kraftfahrzeug mit Schneeketten höchstens fahren ( km/h ) ?
			</question>		 	 
                <answer>50 km/h</answer>
			    <answer>50</answer>            
		</quizentry>
		<quizentry>
			<question>
			 In welchen Zeitabständen muß Ihr PKW ( kein Neufahrzeug, Ottomotor, ohne Kat)
             zur Abgasuntersuchung ( Monate ) ?
            </question>
                <answer>12 Monate</answer>
                <answer>12</answer>               
            </quizentry>
		<quizentry>
			<question>
            An Ihren Kraftfahrzeug ist ein Reifen defekt was müssen sie zuerst tun
            und was zuletzt ? Bringen Sie diese Punkte in die richtige Reihenfolge.
			</question>
			            <sortitem position="4"> 
                            Radmuttern lösen
                        </sortitem>
                        <sortitem position="1">          
                            Warndreieck aufstellen
                        </sortitem>
                        <sortitem position="5">
                            Ersatzrad festschrauben
                        </sortitem>
                        <sortitem position="3">                        
                            Wagenheber aufstellen und hochkurbeln
                        </sortitem>
                        <sortitem position="6">                            
                            Wagenheber herrunterlassen
                        </sortitem>
                        <sortitem position="2">
                            Radmutter nur leicht lockern
                        </sortitem>                     
            </quizentry>
		<quizentry>
			<question>
			    Sie kommen als erster an eine Unfallstelle
                Orden Sie diese Schritte in die richtige Reihenfolge.
             </question>
                          <sortitem position="4">             
                             Krankenwagen und Polizei rufen
                          </sortitem>
                          <sortitem position="1">                
                             Warndreieck aufstellen ( Unfallstelle sichern )
                          </sortitem>
                          <sortitem position="2">                
                             Nach den Verletzten sehen
                          </sortitem>
                          <sortitem position="3">                 
                             Erste Hilfemasnahmen einleiten
                          </sortitem>  
             </quizentry>
	</questionset>
</quiz>

=== BackupTheBerlios/quiztestxml/quiz/xml/mctest1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quiztext SYSTEM "http://www.ccls-online.de/2003/quiztext-0.1.dtd"><quiz>
	<questionset language="de" SID="inti0">
		<creation_date>
		2003-06-20
		</creation_date>
		<editor>
			<name>
			Stefan Bischoff
			</name>
			<email>
			giftnudel185@web.de
			</email>
		</editor>
		<title>
		Intelligenztest
		</title>
		<abstract>
		Hier werden mal Fragen gestellt die Eigentlich etwas unlogisch klingen !!!
		</abstract>
		<quizentry>
			<question>
			 Rolf's Mutter hat 3 Kinder Tick, Trick ?
			</question>
			<choice correct="false">
			 Heinz
			</choice>
			<choice correct="true">
			 Rolf
			</choice>
			<choice correct="false">
			 Karsten
			</choice>
			<choice correct="false">
			 Dennis
			</choice>
			<choice correct="false">
			 Doris
			</choice>
		</quizentry>
		<quizentry>
			<question>
			 Wer tritt uns ungefragt ins Gesicht ?
			</question>
			<choice correct="false">
			 ein Kickboxer
			</choice>
			<choice correct="false">
			 der Sonnenschein
			</choice>
			<choice correct="true">
			 das Alter
			</choice>
			<choice correct="false">
			 die Leute
			</choice>
			<choice correct="false">
			 das Spiegelbild
			</choice>
		</quizentry>
		<quizentry>
			<question>
			 Was sitzt auf der Wiese,ist grün und macht "muh" ?
			</question>
			<choice correct="false">
			 grüne Kuh
			</choice>
			<choice correct="true">
			 Frosch mit Sprachfehler
			</choice>
			<choice correct="false">
			 die Wiese
			</choice>
		</quizentry>
		<quizentry>
			<question>
			 Was ist das Gegenteil von Frühlingserwachen ?
			</question>
			<choice correct="false">
			 im Winter einschlafen
			</choice>
			<choice correct="false">
			 im Sommer einschlafen
			</choice>
			<choice correct="true">
			 Spät rechts einschlafen
			</choice>
			<choice correct="false">
			 im Herbst einschlafen
			</choice>
		</quizentry>
		<quizentry>
			<question>
			 Wie heißt der Schutzpatron der Glöckner ?
			</question>
			<choice correct="true">
			 der heilige Bimbam
			</choice>
			<choice correct="false">
			 Papst
			</choice>
			<choice correct="false">
			 Gerhard Schröder
			</choice>
			<choice correct="false">
			 Mönch
			</choice>
			<choice correct="false">
			 Kirchenchor
			</choice>
		</quizentry>
		<quizentry>
			<question>
			 Ein deutscher Dichter benötigte Jahre dazu, Ihr nichtmal eine Sekunde. Was ist das?
			</question>
			<choice correct="false">
			 Goethe
			</choice>
			<choice correct="false">
			 Schiller
			</choice>
			<choice correct="true">
			 Faust
			</choice>
		</quizentry>
		<quizentry>
			<question>
			 Wieviele Brötchen kann man auf nüchternen Magen essen ?
			</question>
			<choice correct="true">
			 eins
			</choice>
			<choice correct="false">
			 zwei
			</choice>
			<choice correct="false">
			 drei
			</choice>
			<choice correct="false">
			 vier
			</choice>
			<choice correct="false">
			 fünf
			</choice>
		</quizentry>
		<quizentry>
			<question>
			 Wenn sie nur ein Streichholz haben und einen dunklen Raum betreten
     was w&uuml;rden Sie zuerst anzünden ?
			</question>
			<choice correct="false">
			 Öllampe
			</choice>
			<choice correct="false">
			 Karbidlampe
			</choice>
			<choice correct="true">
			 Streichholz
			</choice>
			<choice correct="false">
			 Holzofen
			</choice>
		</quizentry>
		<quizentry>
			<question>
			 Wieviele Geburtstage hat ein normaler Mensch ?
			</question>
			<choice correct="false">
			 viele
			</choice>
			<choice correct="false">
			 ca. 20 bis 30
			</choice>
			<choice correct="false">
			 ca. 40 bis 50
			</choice>
			<choice correct="false">
			 ca. 60 bis 70
			</choice>
			<choice correct="true">
			 einen
			</choice>
			<choice correct="false">
			 keinen
			</choice>
		</quizentry>
		<quizentry>
			<question>
			 Warum kann es nie 2 Tage hintereinander regnen ?
			</question>
			<choice correct="false">
			 wegen Niederschlag
			</choice>
			<choice correct="false">
			 wegen der Sonne
			</choice>
			<choice correct="false">
			 wegen dem Mond
			</choice>
			<choice correct="true">
			 wegen der Nacht
			</choice>
		</quizentry>
		<quizentry>
			<question>
			 Wieviele Dreiecke sind in der Figur enthalten ?
			</question>
			<image ref="figur1.jpg" />
			<answer>
			 35
			</answer>
		</quizentry>
		<quizentry>
			<question>
			 Vor mir fährt die Polizei, hinter mir eine Kutsche.
      Rechts von mir ein Flugzeug, links von mir ein Pferd.
      Wo bin ich ?
			</question>
			<choice correct="false">
			 auf einem Bauernhof
			</choice>
			<choice correct="false">
			 im Strassenverkehr
			</choice>
			<choice correct="true">
			 auf dem Kinderkarussell
			</choice>
		</quizentry>
		<quizentry>
			<question>
			 Je mehr es bekommt, desto hungriger wird es.
      Hat es aber alles gefressen,so stirbt es. Was ist das ?
			</question>
			<choice correct="false">
			 eine Neunköpfige Raupe
			</choice>
			<choice correct="false">
			 ein Schwarm Heuschrecken
			</choice>
			<choice correct="false">
			 Piranhas
			</choice>
			<choice correct="false">
			 Aktenvernichter
			</choice>
            <choice correct="true">
             Feuer 
			</choice>
		</quizentry>
		<quizentry>
			<question>
			 Was war am 06.12.1934 ?
			</question>
			<choice correct="false">
			 Reichstagsbrand
			</choice>
			<choice correct="true">
			 Nikolaus
			</choice>
			<choice correct="false">
			 Bücherverbrennung
			</choice>
			<choice correct="false">
			 Mauerfall
			</choice>
			<choice correct="false">
			 Sonnenfinsternis
			</choice>
		</quizentry>
		<quizentry>
			<question>
			 Wieviele Tiere jeder Art hat Moses mit in die Arche genommen ?
			</question>
			<choice correct="false">
			 2 Tiere
			</choice>
			<choice correct="false">
			 3 Tiere
			</choice>
			<choice correct="false">
			 4 Tiere
			</choice>
			<choice correct="false">
			 1 Tier
			</choice>
			<choice correct="true">
			 Kein Tier
			</choice>
		</quizentry>
	</questionset>
</quiz>

=== BackupTheBerlios/quiztestxml/quiz/xml/ltestM.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quiztext SYSTEM "http://www.ccls-online.de/2003/quiztext-0.1.dtd"><quiz>
	<questionset SID="ltestM0">
		<creation_date>
		2003-06-20
		</creation_date>
		<editor>
			<name>
			Irgend Einer
			</name>
			<email>
			Irgend@irgend.de
			</email>
		</editor>
		<title>
		 Liebestest:(männlich)
		</title>
		<abstract>
		Test mit ungewissen Ausgang und verschieden Antwortmöglichkeiten.
		</abstract>
		<quizentry>
			<question>
			Wann haben Sie eine Frau zu ersten mal geküsst ?
			</question>
			<test value="5">
			zwischen 10 bis 15 Jahren
			</test>
			<test value="4">
			zwischen 15 bis 25 Jahren
			</test>
			<test value="3">
			zwischen 25 bis 35 Jahren
			</test>
			<test value="2">
			zwischen 35 bis 45 Jahren
			</test>
			<test value="1">
			noch nie
			</test>
			<hint>
			 früh übt sich 5 Punkte
			</hint>
			<hint>
			 besser spät als nie 4 Punkte
			</hint>
			<hint>
			 naja  3 Punkte
			</hint>
			<hint>
			 lol 2 Punkte
			</hint>
			<hint>
			 naja das wird schon noch 1 Punkt
			</hint>
		</quizentry>
		<quizentry>
			<question>
			Wieviele Frauen haben Sie schon gehabt ?
			</question>
			<test value="3">
			 eine
			</test>
			<test value="4">
			viele
			</test>
			<test value="1">
			zähle ich nicht
			</test>
			<test value="2">
			keine
			</test>
			<hint>
			 immerhin 3 Punkte
			</hint>
			<hint>
			 Loverboy 4 Punkte
			</hint>
			<hint>
			 Hochstapler 1 Punkt
			</hint>
			<hint>
			 2 Trostpunkte
			</hint>
		</quizentry>
		<quizentry>
			<question>
			Welche Haarfarbe bevorzugen Sie bei Frauen ?
			</question>
			<test value="5">
			Blond
			</test>
			<test value="5">
			Schwarz
			</test>
			<test value="5">
			Braun
			</test>
			<test value="5">
			Bruinette
			</test>
			<test value="1">
			mir egal
			</test>
			<hint>
			 5 Punkte
			</hint>
			<hint>
			 5 Punkte
			</hint>
			<hint>
			 5 Punkte
			</hint>
			<hint>
			 5 Punkte
			</hint>
			<hint>
			 1Punkt
			</hint>
		</quizentry>
		<quizentry>
			<question>
			Was gefällt ihnen an Frauen besonders ?
			</question>
			<test value="2">
			Der Po
			</test>
			<test value="3">
			Die Augen
			</test>
			<test value="4">
			Die Brüste
			</test>
			<test value="1">
			Der Charakter
			</test>
			<test value="5">
			Alles
			</test>
			<hint>
			 aha 2 Punkte
			</hint>
			<hint>
			 was guckst du 3 Punkte
			</hint>
			<hint>
			 oohh 4 Punkte
			</hint>
			<hint>
			 welcher hihi 1 Punkt
			</hint>
			<hint>
			 jupp 5 Punkte
			</hint>
		</quizentry>
		<quizentry>
			<question>
			Wie macht man eine Frau sofort Glücklich ?
			</question>
			<test value="1">
			Man schenkt Ihr Blumen
			</test>
			<test value="5">
			Gibt ihr Zugang zum Konto
			</test>
			<test value="2">
			Sagt ihr jeden Tag wie hübsch Sie ist
			</test>
			<test value="4">
			Man Vergisst nie ihren Geburtstag
			</test>
			<test value="3">
			Man geht mit ihr shoppen
			</test>
			<hint>
			 1 Punkte
			</hint>
			<hint>
			 5 Punkte
			</hint>
			<hint>
			 2 Punkte
			</hint>
			<hint>
			 4 Punkte
			</hint>
			<hint>
			 3 Punkte
			</hint>
		</quizentry>
                <result minimum="0" maximum="5">
               Sie sind ein hoffnungsloser Fall.   
                </result>
                <result minimum="6" maximum="10">
             Die Hoffnung stirbt zuletzt.
                </result>
                <result minimum="11" maximum="15">
                 Naja man lernt halt nie aus.
                </result>
                <result minimum="16" maximum="20">
                 Sie kennen sich mit Frauen gut aus.
                </result>
                <result minimum="21" maximum="25">
                 Sie sind für Frauen eine gute Partie.
                </result>
	</questionset>
	<questionset SID="ltestW0">
		<creation_date>
		2003-06-20
		</creation_date>
		<editor>
			<name>
			Irgend Einer
			</name>
			<email>
			Irgend@irgend.de
			</email>
		</editor>
		<title>
		 Liebestest:(weiblich)
		</title>
		<abstract>
		Test mit ungewissen Ausgang und verschieden Antwortmöglichkeiten.
		</abstract>
		<quizentry>
			<question>
			Wann haben Sie einen Mann zu ersten mal geküsst ?
			</question>
			<test value="5">
			zwischen 10 bis 15 Jahren
			</test>
			<test value="4">
			zwischen 15 bis 25 Jahren
			</test>
			<test value="3">
			zwischen 25 bis 35 Jahren
			</test>
			<test value="2">
			zwischen 35 bis 45 Jahren
			</test>
			<test value="1">
			noch nie
			</test>
			<hint>
			 früh übt sich 5 Punkte
			</hint>
			<hint>
			 besser spät als nie 4 Punkte
			</hint>
			<hint>
			 naja  3 Punkte
			</hint>
			<hint>
			 lol 2 Punkte
			</hint>
			<hint>
			 naja das wird schon noch 1 Punkt
			</hint>
		</quizentry>
		<quizentry>
			<question>
			Wieviele Männer haben Sie schon gehabt ?
			</question>
			<test value="3">
			einen
			</test>
			<test value="4">
			viele
			</test>
			<test value="1">
			zähle ich nicht
			</test>
			<test value="2">
			keinen
			</test>
			<hint>
			 immerhin 3 Punkte
			</hint>
			<hint>
			 4 Punkte
			</hint>
			<hint>
			naja 1 Punkt
			</hint>
			<hint>
			 2 Trostpunkte
			</hint>
		</quizentry>
		<quizentry>
			<question>
			Welche Haarfarbe bevorzugen Sie bei Männern ?
			</question>
			<test value="5">
			Blond
			</test>
			<test value="5">
			Schwarz
			</test>
			<test value="5">
			Braun
			</test>
			<test value="5">
			Bruinette
			</test>
			<test value="1">
			mir egal
			</test>
			<hint>
			 5 Punkte
			</hint>
			<hint>
			 5 Punkte
			</hint>
			<hint>
			 5 Punkte
			</hint>
			<hint>
			 5 Punkte
			</hint>
			<hint>
			 1Punkt
			</hint>
		</quizentry>
		<quizentry>
			<question>
			Was gefällt ihnen an Männern besonders ?
			</question>
			<test value="4">
			Der Po
			</test>
			<test value="3">
			Die Augen
			</test>
			<test value="2">
			Die Brustbehaarung
			</test>
			<test value="1">
			Der Charakter
			</test>
			<test value="5">
			Alles
			</test>
			<hint>
			 aha 4 Punkte
			</hint>
			<hint>
			 was guckst du 3 Punkte
			</hint>
			<hint>
			 oohh 2 Punkte
			</hint>
			<hint>
			 1 Punkt
			</hint>
			<hint>
			 jupp 5 Punkte
			</hint>
		</quizentry>
		<quizentry>
			<question>
			Wie macht man einen Mann sofort Glücklich ?
			</question>
			<test value="1">
			Man holt Ihn sein Bier und die Hausschuhe
			</test>
			<test value="5">
			Das Fussballspiel in Ruhe schauen lassen
			</test>
			<test value="2">
			Seine Freunde zuhause Einladen
			</test>
			<test value="4">
			Das essen ist fertig
			</test>
			<test value="3">
			Ihn Ausschlafen lassen
			</test>
			<hint>
			 1 Punkte
			</hint>
			<hint>
			 5 Punkte
			</hint>
			<hint>
			 2 Punkte
			</hint>
			<hint>
			 4 Punkte
			</hint>
			<hint>
			 3 Punkte
			</hint>
		</quizentry>
                <result minimum="0" maximum="5">
                Ohne Fleiss kein Preis. 
                </result>
                <result minimum="6" maximum="10">
                 Die Hoffnung stirbt zuletzt. 
                </result>
                <result minimum="11" maximum="15">
               Naja man lernt halt nie aus.
                </result>
                <result minimum="16" maximum="20">
                 Sie bekommen jeden. 
                </result>
                <result minimum="21" maximum="25">
                  Sie sind für Männer die Traumfrau.
                </result>
	</questionset>
</quiz>

=== BackupTheBerlios/quiztestxml/quiz/xml/biologiequiz.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quiztext SYSTEM "quiztext-0.1.dtd"><quiz>
<questionset SID="Tiere0" source="http://encarta.msn.de">
		<creation_date>
		2003-07-02
		</creation_date>
		<editor>
			<name>
			Stefan Bischoff
			</name>
			<email>
			giftnudel185@web.de
			</email>
		</editor>
		<title>
		 Biologiequiz
		</title>
                <abstract>Fragen aus dem Gebiet der Biologie.</abstract>
                <quizentry>
			<question>Aus welchen chemischen Stoff besteht das Schlangengift ?</question>
                        <image ref="schlange1.jpg"></image>
			<choice correct="true">komplexe Mischung aus Eiweißen</choice>
			<choice correct="false">komplexe Mischung aus Magensäften</choice>
			<choice correct="false">komplexe Mischung aus Speichelenzymen</choice>
		</quizentry>
                <quizentry>
                        <question>Um welche Zeit begann die Einführung von Hauspferden ?</question>
                        <image ref="pferd.jpg"></image>
                        <choice correct="false">1000 Jahre v.Chr.</choice>
                        <choice correct="true">2000 Jahre v.Chr.</choice>
                        <choice correct="false">3000 Jahre v.Chr.</choice>
                        <choice correct="false">4000 Jahre v.Chr.</choice>
                </quizentry>
                <quizentry>
                        <question>Wieviele Arten von Skorpionen gibt es ?</question>
                        <image ref="skorpion.jpg"></image>
                         <choice correct="false">300 Arten</choice>
                         <choice correct="false">400 Arten</choice>
                         <choice correct="false">500 Arten</choice>
                         <choice correct="false">600 Arten</choice>
                         <choice correct="true">700 Arten</choice>
                </quizentry>
                <quizentry>
                        <question>Wie zerkleinern Schildkröten ihre Nahrung ?</question>
                        <image ref="schildkr.jpg"></image>
                         <choice correct="false">Zähne</choice>
                         <choice correct="true">Hornscheiden</choice>
                         <choice correct="false"> Speichelenzyme</choice>
                         <choice correct="false">keine Zerkleinerung</choice>
               </quizentry>
                <quizentry>
                        <question>Von welcher Tiergattung stammen urgeschichtlich die Federn bei Vögeln ab ?</question>
                         <image ref="voegel.jpg"></image>
                        <choice correct="false">Meerestiere</choice>
                         <choice correct="false">Säugetiere</choice>
                         <choice correct="true">Reptilien</choice>
                </quizentry>
                 <quizentry>
                        <question>Wieviele lebendige Junge bringt eine Anakonda zur Welt ?</question>
                        <image ref="schlange2.jpg"></image>
                         <choice correct="false">10 Junge</choice>
                         <choice correct="false">20 Junge</choice>
                         <choice correct="true">30 Junge</choice>
                </quizentry>
                <quizentry>
                        <question>Wo ist der Lebensraum des Tiegers ?</question>
                        <image ref="tiger.jpg"></image>
                         <choice correct="true">Asien</choice>
                         <choice correct="false">Australien</choice>
                         <choice correct="false">Afrika</choice>
                         <choice correct="false">Südamerika</choice>
               </quizentry>
                 <quizentry>
                        <question>Wie schwer kann ein Löwe werden ?</question>
                        <image ref="loewe1.jpg"></image> <image ref="loewe2.jpg"></image>
                         <choice correct="false">50 bis 150 Kilogramm</choice>
                         <choice correct="true">150 bis 250 Kilogramm</choice>
                         <choice correct="false">250 bis 350 Kilogramm</choice>
                </quizentry>
                <quizentry>
                        <question>In welchen Gebieten kommen Fleisch fressende Pflanzen vor ?</question>
                        <image ref="flfrpfla1.jpg"></image>
                        <image ref="flfrpfla2.jpg"></image>
                         <choice correct="true">Sümpfen</choice>
                         <choice correct="false">Wäldern</choice>
                         <choice correct="false">Wiesen</choice>
                </quizentry>
                <quizentry>
                        <question>Wieviele Arten von Insekten gibt es ( bis heute bekannt ) ?</question>
                        <image ref="insekt1.jpg"></image><image ref="insekt2.gif"></image>
                         <choice correct="true"> 1 Millionen</choice>
                         <choice correct="false">2 Millionen</choice>
                         <choice correct="false">3 Millionen</choice>
                         <choice correct="false">4 Millionen</choice>
               </quizentry>
        </questionset>
</quiz>
